language: java
jdk:
  - oraclejdk8

addons: # get google-chrome-stable
  chrome: stable

install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
  
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - ./gradlew check
  - ./gradlew test
  - ./gradlew selenium
  
deploy:
  provider: heroku
  api_key: '7a8cdcaf-b626-46ca-8474-221b4c99e93b'
  app: floating-sea-50974
  
after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  chrome: stable

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.11.1/geckodriver-v0.11.1-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.11.1-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$PWD/geckodriver